name: C++ Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # 每周一运行
  workflow_dispatch:

jobs:
  format-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format clang-tidy cppcheck
    
    - name: Run clang-format
      run: |
        find . -name '*.cpp' -or -name '*.h' | xargs clang-format -i --style=file
        git diff --exit-code
    
    - name: Run clang-tidy
      run: |
        find . -name '*.cpp' | xargs clang-tidy
    
    - name: Run cppcheck
      run: |
        cppcheck --enable=all --error-exitcode=1 .
